### ISSUE TITLE
Question: Serial receive buffer size

### ISSUE THREAD

**Issue by nedoskiv** [MCUdude/MiniCore#104]
Hello,

Sorry for opening an issue to ask a question, but what is default uart/serial receive buffer size and how can it be change. Also while I was browsing library folders notice that there is software serial, same question about it.

Thank you for your time.

**Comment by MCUdude** [comment]
It's just like in the official Arduino core files. You can find the serial buffer size definition for hardware Serial [here](https://github.com/MCUdude/MiniCore/blob/f7982c04f1d0d73a429b9e8027ec12d4ec3f5e0d/avr/cores/MCUdude_corefiles/HardwareSerial.h#L42-L55) and for SoftwareSerial [here](https://github.com/MCUdude/MiniCore/blob/f7982c04f1d0d73a429b9e8027ec12d4ec3f5e0d/avr/libraries/SoftwareSerial/src/SoftwareSerial.h#L59-L61). Note that there is no SoftwareSerial TX buffer because SoftwareSerial is bit-banged.

**Comment by nedoskiv** [comment]
thank you
