### ISSUE TITLE
Atmega328pb 16MHz external crystal bootloader issues

### ISSUE THREAD

**Issue by 818Mainstream** [MCUdude/MiniCore#119]
Just wondering if anyone had any issues with burning the bootloader with an external crystal oscillao like this one cb3-3i-16m0000. My issue is that it will not burn unless I load the output with some capacitance in the range.of 14pF to 40pF. Verify weird issue I've never seen before since I've only used them before with 8MHz internal. I'm using an Arduino uno in isp as the loader

**Comment by MCUdude** [comment]
The ATmega328PB (and the bigger ATmega324PB) lacks an external oscillator full swing option. This means that it will be very picky on what external crystal it will be able to drive.

I don't know what crystal to recommend, but find one that requires a small capacitive load. IIRC the maximum recommended capacitance is 22pF, but you can find some guidelines in the datasheet. If you need more help regarding this, you should perhaps ask on the Avrfreaks forum. Those guys know their stuff.

I recently designed a commercial product based around an ATmega324PB with an external resonator with built-in caps. Sadly, the assembly house had mounted a resonator with 30pF capacitance instead of the specified 10pF. They did work when they were tested, but some units would suddenly crash after a few days. It was a stupid move from Atmel to remove the full-swing oscillator option on these chips 🙁
