### ISSUE TITLE
Unclear operation "no bootloader" setting

### ISSUE THREAD

**Issue by lotrbuilders** [MCUdude/MiniCore#138]
This is more of a question theb an actual issue, but this is still unclear in the readme file. 
What exactly happens when the "no bootloader" setting is selected. Can one still program the chip afterwards and if so how? What exact things can not be used or do you have to do yourself when there is no bootloader?
Thanks in advance for any clarification

**Comment by MCUdude** [comment]
The bootloader lets you upload to your chip using a UART interface. This is very convenient because you can use a standard USB to serial chip rather than a dedicated programmer. The downside, however, is that the bootloader occupies 512 bytes of the flash memory at all times.

**With the bootloader:**
* Upload using a USB to serial chip/adapter
* Occupies 512 bytes at all times

**Without bootloader:**
* You will have to upload code using a dedicated programmer, such as USBasp, USBtinyISP etc.
* You will have 512 bytes flash memory more since there are no bootloader installed.
