### ISSUE TITLE
Can't upload via Arduino IDE onto a ATmega 328P with the internal oscillator

### ISSUE THREAD

**Issue by scrouthtv** [MCUdude/MiniCore#155]
Hi,

First of all, thanks for the great work.

For a project I'm trying to get this ATmega running without an external oscillator. My project is not time-critical, so I guess I could save some money on the quartz.
Now when I create a very basic circuit with the ATmega *and an external 16 MHz oscillator* and these settings:
![image](https://user-images.githubusercontent.com/23227405/96366781-30dd6580-114a-11eb-8144-ca991e6d24a5.png)
Uploading works fine.
However, when I remove the oscillator and set the `Clock` option to either `Internal 8 MHz`, `Internal 4 MHz`, `Internal 2 MHz` or `Internal 1 MHz`, I get this error:
```
Sketch uses 1462 bytes (4%) of program storage space. Maximum is 32256 bytes.
Global variables use 11 bytes (0%) of dynamic memory, leaving 2037 bytes for local variables. Maximum is 2048 bytes.
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x00
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.
```

In the README, I read to change the baud rate to something lower, so I edited boards.txt#221 to this:
```
328.menu.clock.8MHz_internal.upload.speed=19200
```
And relaunched the IDE. Uploading fails with the same error. Should I try the other internal clocks? With which baud rates?

Do I have to calibrate the internal oscillator? Is there any way to use an external clock for uploading but the internal clock at runtime?

Thanks for any help in advance.

**Comment by scrouthtv** [comment]
Oh also, I think I'm running v2.0.7

**Comment by MCUdude** [comment]
There are several settings you'll have to "Burn Bootloader" in order to load the new settings into the microcontroller. For instance; EEPROM retain, BOD, and clock option. Select the settings you want, and burn the bootloader. The correct bootloader hex file and the correct fuse bits will be loaded, and it will work as expected. You'll need a dedicated programmer to do this.

**Comment by scrouthtv** [comment]
Do I need to burn the bootloader everytime I change the settings? Because I already installed the bootloader using another Arduino and this guide: https://www.arduino.cc/en/Tutorial/BuiltInExamples/ArduinoToBreadboard

**Comment by MCUdude** [comment]
No, you only need to burn the bootloader once. Does it work using the bootloader if you keep the external oscillator, and use 16 MHz? It may be because the internal oscillator isn't very accurate.

**Comment by scrouthtv** [comment]
Yes, it does work with the oscillator.
If I remove it and change the property in the IDE, I get this error.
I also tried with a lower baudrate

**Comment by MCUdude** [comment]
OK. I'll wire up a board exactly as you describe it and see if I run into the same problem. If I don't, it is because the internal oscillator in your chip is probably a bit too slow. I'll keep you updated.

**Comment by scrouthtv** [comment]
This is what I did in the first step:
 
![1_diagram](https://user-images.githubusercontent.com/23227405/97198807-8996a900-17af-11eb-8b6f-c3823688cbd4.png)

Uploading works fine.

When I remove XT I get the error above.

Thanks for your help in advance

**Comment by MCUdude** [comment]
I did test this on an ATmega328P, and everything worked fine.

* Install the 16 MHz oscillator and burn the bootloader. Verify that everything is working by uploading to the microcontroller using the USB to serial adapter
* Select these settings
  <img width="320" alt="Skjermbilde 2020-10-26 kl  19 33 06" src="https://user-images.githubusercontent.com/3238730/97213580-13e80880-17c2-11eb-9550-5d01c3d9dcb8.png">
* Burn the bootloader again, with the 16 MHz crystal installed
* Remove the crystal. If you connect an LED to digital pin 13, it should flash twice if you reset the microcontroller
* Try uploading using the USB to serial adapter

**Comment by SpenceKonde** [comment]
Any time you change the Clock, BOD, EEPROM, or Bootloader options, you must burn bootloader again in order to set the fuses correctly (with very few exceptions- changing between two crystals of different speed, but within the same "speed bracket" in terms of the CSEL bits of lfuse, or between two different speeds derived from the internal 8 MHz oscillator neither of which are 1 MHz, unless it's a tiny4313 or tiny2313, which has two internal oscillators... and if that made your head spin, well, that's why I tell people to always burn bootloader if they change any of those options on any classic* AVR).  

* classic being anything released before 2016; the modern AVRs have a radically different architecture; the parts supported by megaTinyCore and MegaCoreX don't need you to burn bootloader when changing clock speed unless you're changing to or from a speed divisible by 5 - and the latest and greatest in the land of AVRs, the Dx-series, supported by DxCore, never need you to butrn bootloader to change clock speed/source... You see, it's all very simple and straightforward! Clear as crystal! >.>

**Comment by scrouthtv** [comment]
Ok, I will try that as soon as I'm back home. Thanks for the help!

**Comment by MCUdude** [comment]
So, how did it go?

**Comment by ajinkya-open** [comment]
I witnessed the same not able to upload by internal acillator, if any one guide how to check it, i would like to contribute in the this project,
so if any one has idea, inform me i can check any modifications

**Comment by cburstedde** [comment]
> ![1_diagram](https://user-images.githubusercontent.com/23227405/97198807-8996a900-17af-11eb-8b6f-c3823688cbd4.png)

This may not answer any question, but depending on what the XT device is, it might require additional capacitors from each TOSCX to ground. The usual crystals for example work with two 18pF or 22pF caps. And, at the risk of being trivial, a 100nF capacitor between VCC and ground is also required.

**Comment by pfeerick** [comment]
I was just flashing some 16Mhz EXT OSC ATMega328s to 1Mhz INT OSC yesterday, hence did the burn bootloader because of changed fuse settings. It appears I also need to use the low speed USBASP option when programming via ISP otherwise the target will not be detected. I didn't need to change any `boards.txt` settings to upload via serial - flashing the bootloader, which also sets the correct clock fuses, is all that was needed when changing speeds.

**Comment by cimba007** [comment]
Got the same problem .. with internal OSC I am not able to upload any sketch. This somehow lead me back to some posts from tha past ... https://github.com/Optiboot/optiboot/issues/209 still not shure if it is related.

**Comment by duraluminium** [comment]
I experienced a similar error, I know the thread is old but maybe this will help others landing here. After burning bootloader, in order to upload a sketch you have to either Shift+Upload or select **"Upload with programmer"** from the menu bar! Clicking "upload" will try and upload to the programmer/arduino, NOT the 328 chip being targeted. The error results from wrong parameters the arduino doesn't accept.

**Comment by MCUdude** [comment]
I'm closing this issue because OP hasn't replied in a long time, and it's most likely a hardware issue.

The issue @pfeerick pointed out where a slow programmer option had to be used is a known "issue" with the USBasp programmer. Its default speed is too fast for an AVR running at 1 MHz.

@duraluminium's fix doesn't really solve the issue here, because he's uploading using a programmer rather than trying to get the bootloader to work.

**Comment by scrouthtv** [comment]
> OP hasn't replied in a long time

Didn't find the time for this as I started university. Might get back to this at some time later, but closing is fine with me.
