### ISSUE TITLE
atmega 8  rcswitch

### ISSUE THREAD

**Issue by tamer1526** [MCUdude/MiniCore#203]
atmega8 not working with rcswitch library tested

**Comment by MCUdude** [comment]
That's not much of a clue for me to work on. You need to give me the URL where I can fin the library, ideally post your code and the error message the compiler gives you.

**Comment by tamer1526** [comment]
the link of the library https://github.com/sui77/rc-switch
the code demo simple reciver not working for atmega8 and it work perfect for atmega328
  if (rfc.available()) {
    Serial.print("Received ");
    Serial.print( rfc.getReceivedValue() );
    Serial.print(" / ");
    Serial.print( rfc.getReceivedBitlength() );
    Serial.print("bit ");
    Serial.print("Protocol: ");
    Serial.println( rfc.getReceivedProtocol() );
    rfc.resetAvailable();
  }

**Comment by MCUdude** [comment]
Are you getting an error from the compiler, or does it compile just fine, but doesn't work?

**Comment by tamer1526** [comment]
no compiling errors but it doesnt work

**Comment by MCUdude** [comment]
I don't have any rc-switch compatible hardware, so I'm not able to test it with real hardware. However, not all libraries will work with aTmega8 because the author hasn't designed the library to work with it, You should open an issue over at the rc-switch Github repo and explain what issues you're facing and how they can reproduce the issue. They might be able to help you.
