### ISSUE TITLE
Atmega328P U works, but only in Arduino Uno, not on breadboard.

### ISSUE THREAD

**Issue by MadPanCake** [MCUdude/MiniCore#241]
Hello,

I'm struggling with this issue for at least 3 days. Every day trying for hours to fix it. I would be the happiest person on earth if someone managed to help me.

I've bought 10x Atmega328P U from AliExpress to use them for my electronic projects.
I've burned a bootloader on them, via Arduino IDE's default code, via Gammon's bootloader code and using MiniCore's bootloader.
All worked, and my Atmega was working fine, **as long as it was plugged into Arduino** UNO's DIP.

The moment I've put it on a breadboard, it was doing nothing at all.
The **breadboard wiring is correct**, because I have an Arduino Uno that came with a removable Atmega328P U and this one Atmega works fine on that breadboard.

I'm using a full setup, so a resistor on reset PIN, 16MHZ oscillator and 2 capacitors.
![315116872_670575274517310_1585201762544774532_n (1)](https://user-images.githubusercontent.com/34662922/202454415-4d1ee0ad-28b5-452b-b339-b33d03fca37e.jpg)
![315175132_833362781274892_6773007521733870942_n (1)](https://user-images.githubusercontent.com/34662922/202454426-a7c9aaa7-127c-4cc3-b4e4-2551c762a74c.jpg)

**Comment by MCUdude** [comment]
> The moment I've put it on a breadboard, it was doing nothing at all.
The breadboard wiring is correct, because I have an Arduino Uno that came with a removable Atmega328P U and this one Atmega works fine on that breadboard.

If you look at the minimal setup schematic I've provided for MiniCore, it's pretty clear that your setup doesn't match this.
Your breadboard is lacking decoupling capacitors close to the Vcc and GND pins. The 15/18/22/27pF capacitors connected to the crystal should be connected directly to the GND pin on the microcontroller and not to the ground strip on the side.

**Comment by MCUdude** [comment]
There's no way around getting your hardware right

**Comment by MCUdude** [comment]
The problem is that you have a flakey hardware setup that works with some chips, but not for the ones from AliExpress. It's clearly something with your hardware setup that causes this, or it might be possible that your chips from AliExpress are "2nd grade" with internal defects.

But if you want to get rid of potential sources of error try switching to the internal 8 or 1 MHz oscillator. This way it's not depending on a crystal that _might_ not like the capacitance in the breadboard all that much.

Either way, MiniCore is not causing this issue, so you should ask on the Arduino forum where there are more people that can help you.
