### ISSUE TITLE
print floats or doubles of printf can be implemented according to ChaN's xprintf

### ISSUE THREAD

**Issue by wanggaoteng** [MCUdude/MiniCore#257]
Hi, @hansibull 
Thank you for providing this great work. The "generic" AVR programming of miniCore is very popular among students, now the students can program generic avr c code or arduino code in one ide, this is very convenient.
By the way, print floats or doubles of printf can be implemented according to ChaN's [xprintf](http://elm-chan.org/fsw/strf/xprintf.html), the attachments are the code. The code can be optimized for printing floats or doubles.
I don't know how to upload files here, so the attachments for atmega328p are post [here](https://www.avrfreaks.net/s/topic/a5C3l000000BoAFEA0/t390616). Hope it may help.
Best regards.

``` cpp
#include "avr/io.h"
#include "util/delay.h"
#include "functions.h"
#include "xprintf.h"
 
int main(void) 
{
    int i=0;
    avr_uart_init();
    xdev_out(avr_uart_putchar);
    while(1)
    {
            xprintf("%d\n",i++);
            xprintf("%.3f\n",1.23);
            _delay_ms(1000);
     }
      return 0;
  }
```
![image](https://github.com/MCUdude/MiniCore/assets/29191854/7587b729-651d-46d3-bf7d-d3a8b2fa4d77)

**Comment by MCUdude** [comment]
Great to hear it's popular among students!

printing floats are disabled by default, because it occupies about 1.5 kB of flash, even when only printing fixed point numbers. However, if you're using PlatformIO it can easily be enabled by [specifying a compiler flag](https://github.com/MCUdude/MiniCore/blob/master/PlatformIO.md#build_flags-1).
