### ISSUE TITLE
No separate SPDR0 SPDR1 for the ATMega328PB?

### ISSUE THREAD

**Issue by fxframes** [MCUdude/MiniCore#285]
Hi, apologies if I got this wrong.
I'm working on a project that uses the SPI0 pins on a 328PB as slave for initial programming and then as master for communicating with an MCP4921. I didn't realize at first that I could use SPI1 for the second purpose, but my question still stands.
The SPCR register in the 328P has become SPCR0 /1 in the 328PB, but we seem to be missing definitions for the latter?
This is because regardless of using pre-made libraries or direct instructions I can't seem to make the MCP4921 work so I'm trying all possibilites.

This compiles:

``` c
void SPI_MasterInit(void)
{
   /* Set MOSI and SCK output, all others input */
   DDRB = (1<<DDB3)|(1<<DDB5);
   /* Enable SPI, Master, set clock rate fck/16 */
   SPCR = (1<<SPE)|(1<<MSTR)|(1<<SPR0);
}
```

But this doesn't:

```c
void SPI_MasterInit(void)
{
   /* Set MOSI and SCK output, all others input */
   DDRB = (1<<DDB3)|(1<<DDB5);
   /* Enable SPI, Master, set clock rate fck/16 */
   SPCR0 = (1<<SPE0)|(1<<MSTR0)|(1<<SPR00);
}
```
Thanks for any insights.

**Comment by MCUdude** [comment]
I you look at the iom328pb.h file that the avr-gc compiler uses, you can see what's defined and what's not.
My file is located at (boards manager install on Windows):
`C:\Users\Hans\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7\avr\include\avr\iom328pb.h`

I've also added some compatibility macros here, but it seems like the iom328pb.h file has changed since then.
https://github.com/MCUdude/MiniCore/blob/d46c83fca2612e66d3059f8bb8277ee56bf20d72/avr/variants/pb-variant/pins_arduino.h#L289-L313

**Comment by fxframes** [comment]
Thanks!

**Comment by steike93** [comment]
The fix from MCUDude seemed to fix the definition issue with SPCR0/1, however bit SPIE0, SPE0 is still unrecognized in Microchip studio in my case for ATMEGA328PB. 

Is the workaround to write: 

`SPCR0 |= (1 << SPE) | (1<<MSTR) | (1<<SPR0);`

Instead of : 

`SPCR0 |= (1 << SPE0) | (1<<MSTR0) | (1<<SPR0);`
